.TH PIREAL 1
.SH NAME

A free cross-platform tool for working with Relational Algebra

.SH SYNOPSYS
.B pireal [-v]

.SH DESCRIPTION

Pireal is a teaching tool for use in learning introduction to database. It allows the user to interactively experiment with Relational Algebra.

If it is executed with
.B -v
Log lines to stdout

.SH AUTHOR
Gabriel Acosta <gabriel.acosta@ninja-ide.org>

.SH SEE ALSO
Web site https://centaurialpha.github.io/pireal

Source code https://github.com/centaurialpha/pireal