language: python

python:
  - 3.5
  - 3.6

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install pip --upgrade
  - pip install pytest pytest-qt pytest-cov
  - pip install PyQt5==5.9
  - pip install codecov

before_script: rm --recursive --force --verbose *.py[cod]

script: python run-tests.py

after_succes:
  - codecov
