language: python

python:
    - 3.3
    - 3.4
    - 3.5

before_install:
    - sudo apt-get update
    - sudo apt-get -y install python3-pip
    - sudo pip install --upgrade pip
    - pip install --upgrade pip
    - pip install pep8

script:
    - python -m unittest -v
    - pep8 --exclude='src/resources.py' src -v
