language: python

python:
    - 3.3
    - 3.4
    - 3.5

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    # Install pep8
    #- sudo apt-get update
    #- sudo apt-get -y install python-pip
    #- sudo pip install --upgrade pip
    #- pip install --upgrade pip
    #- pip install pep8
    # Cached Downloads
    - sudo mkdir -p /downloads
    - sudo chmod a+rw /downloads
    - wget --quiet --output-document=downloads/sip.tar.gz http://downloads.sourceforge.net/project/pyqt/sip/sip-4.18/sip-4.18.tar.gz
    - wget --quiet --output-document=downloads/pyqt5.tar.gz http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.5.1/PyQt-gpl-5.5.1.tar.gz
    # Builds
    - sudo mkdir -p /builds
    - sudo chmod a+rw /builds

install:
    # Qt5
    - sudo add-apt-repository -y ppa:beineri/opt-qt542
    - sudo apt-get update
    - sudo apt-get install -y qt54base
    # Builds
    - pushd /builds
    # SIP
    - tar xzf /downloads/sip.tar.gz --keep-newer-files
    - pushd sip-4.18
    - python configure.py
    - make
    - sudo make install
    - popd
    # PyQt5
    - source /opt/qt55/bin/qt55-env.sh  # switch to Qt5
    - tar xzf /downloads/pyqt5.tar.gz --keep-newer-files
    - pushd PyQt-gpl-5.5.1
    - python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui -e QtWidgets
    - make
    - sudo make install
    - popd
    # Builds Complete
    - popd
    # PEP8
    - sudo apt-get -y install python-pip
    - sudo pip install --upgrade pip
    - pip install --upgrade pip
    - pip install pep8

script:
    - ./run_tests

cache:
    directories:
        - /downloads
    apt: true
