language: python

python: 3.7

os: linux
dist: xenial

services:
  - xvfb

cache: pip

installation_on_windows:
- &installation_on_windows
  before_install:
    - choco install python --version 3.7.4
    - python --version
    - python -m pip install --upgrade pip
    - pip3 install --upgrade pyqt5 pytest pytest-qt ordered-set

install: pip --version  # Avoid install with pip install -r requirements.txt

script: echo "Skip global script..."

stages:
  - Static Analisys
  - Test
  - Test GUI
  - Integration Test
  - Coverage

jobs:
  include:
    - stage: Static Analisys
      name: pycodestyle
      before_install:
        - pip install pip --upgrade
        - pip install pycodestyle
      script: make pep8

    - stage: Static Analisys
      name: flake8
      before_install:
        - pip install pip --upgrade
        - pip install flake8
      script: make flake8

    - stage: Test
      name: unit test
      before_install:
        - pip install pip --upgrade
        - pip install pyqt5 pytest pytest-cov ordered-set
      script: make test

    - stage: Test
      name: unit test on windows
      os: windows
      language: shell
      <<: *installation_on_windows
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      script: pytest tests -m "not integration" --ignore=tests/gui

    - stage: Test GUI
      addons:
        apt:
          packages:
            - x11-utils
            - libxkbcommon-x11-0
      name: unit test user interface
      before_install:
        - pip install pip --upgrade
        - pip install pyqt5 pytest pytest-mock pytest-qt ordered-set
      script: make test-gui

    - stage: Integration Test
      addons:
        apt:
          packages:
            - x11-utils
            - libxkbcommon-x11-0
      name: integration test
      before_install:
        - pip install pip --upgrade
        - pip install pyqt5 pytest pytest-qt ordered-set
      before_script: make clean
      script: make test-integration

    - stage: Integration Test
      name: integration test on Windows
      os: windows
      language: shell
      <<: *installation_on_windows
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      script: pytest tests -m integration --ignore=tests/gui

    - stage: Coverage
      name: coverage
      before_install:
        - pip install pip --upgrade
        - pip install pytest pytest-cov coveralls ordered-set
      script: coveralls
