language: python

python:
    - 3.3
    - 3.4
    - 3.5

before_install:
    - sudo apt-get update
    - sudo apt-get -y install python-pip
    - sudo pip install --upgrade pip
    - pip install --upgrade pip
    - pip install pep8

script:
    - ./run_tests
