language: python

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

before_script: make clean

stages:
  - lint
  - test
  - test-gui

jobs:
  include:
    - stage: lint
      python: 3.6
      script: flake8 src
    - stage: test
      name: Unit Tests
      python:
        - 3.5
        - 3.6
      script: make test
    - stage: test-gui
      name: GUI Tests
      python: 3.5
      script: make test-gui
    # - python: 3.5
    # - python: 3.6
    # - stage: lint
    #   python: 3.6
    #   script: flake8 src
    # - stage: test-gui
    #   name: GUI Tests
    #   python: 3.5
    #   script: make test-gui
