language: python

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script: make clean

install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

stages:
  - lint
  - test
  - test-gui

script: make test

jobs:
  include:
    - python 3.5
    - python 3.6
    - stage: lint
      - python: 3.6
      script: flake8 src
    - stage: test-gui
      - python: 3.5
      script: make test-gui
