language: python

python: 3.7

dist: xenial

services:
  - xvfb

before_install:
  - "export DISPLAY=:99.0"

install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

before_script: make clean

script: echo "Skip global script..."

stages:
  - Static Analisys
  - Test
  - Integration Test
  - Coverage

jobs:
  include:
    - stage: Static Analisys
      name: pycodestyle
      script: make pep8
    - stage: Static Analisys
      name: flake8
      script: make flake8
    - stage: Test
      name: unit test
      script: make test
    - stage: Test
      name: test gui
      script: make test-gui
    - stage: Integration Test
      name: integration test
      script: make test-integration
    - stage: Coverage
      name: coverage
      script: coveralls

  matrix:
    include:
      - name: "Testing on Windows"
        os: windows
        language: shell
        before_install:
          - choco install python
          - python --version
          - python -m pip install --upgrade pip
          - pip3 install --upgrade pytest
        script: pytest tests/