build: false

environment:
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.3"
      PYTHON_ARCH: "32"
      
install:
  - pip install pep8

test_script:
  - pep8 --exclude='src/resources.py' src -v
  - python -m unittest -v
