build: false

environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
    
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.3"
      PYTHON_ARCH: "32"
      
install:

test_script:
  - "%CMD_IN_ENV%  python -m unittest -v"
