#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2015 - Gabriel Acosta <acostadariogabriel@gmail.com>
#
# This file is part of Pireal.
#
# Pireal is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# any later version.
#
# Pireal is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pireal; If not, see <http://www.gnu.org/licenses/>.

""" Convert .rdb file to .pdb file """

import sys
import os
import codecs


def read(rdb_file):
    content = codecs.open(rdb_file, 'r', 'iso-8859-1').read()
    return content


def convert(rdb_content):
    content = ""
    for line in rdb_content.splitlines():
        if line.startswith('@'):
            content += "@"
            portion = line.split('(')
            name = portion[0][1:]
            content += name + ':'
            hheader = portion[1].split(':')[0][:-1].split(',')
            header = []
            for field in hheader:
                header.append(field.split('/')[0].strip())
            content += ','.join(header)
        else:
            if not line:
                continue
            for l in line.splitlines():
                l = l.replace("'", '"')
                line = l
            content += line
        content += '\n'

    return content


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python rdb_to_pdb [file.rdb]")
        sys.exit(-1)

    filename = sys.argv[-1]
    print("Reading RDB file...")
    content = read(filename)
    print("Converting RDB to PDB...")
    pdb_content = convert(content)
    new_filename = os.path.join(os.path.dirname(filename),
                                filename[:-3] + 'pdb')
    print("Writing...")
    f = codecs.open(new_filename, 'w', 'utf-8')
    f.write(pdb_content)
    f.close()
    print("Ok!")
