name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12"]

    env:
      QT_QPA_PLATFORM: offscreen
      QT_OPENGL: software
      LIBGL_ALWAYS_SOFTWARE: 1

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install the project
        run: |
          uv sync --all-extras --dev
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt-get update -y
            sudo apt-get install -y \
              libgl1 \
              libegl1 \
              libxkbcommon-x11-0 \
              libxcb-cursor0 \
              libxcb-icccm4 \
              libxcb-keysyms1 \
              libxcb-image0 \
              libxcb-shm0 \
              libxcb-randr0 \
              libxcb-render-util0 \
              libxcb-xinerama0 \
              libxcb-xkb1 \
              libxkbcommon0 \
              libfontconfig1 \
              libdbus-1-3 \
              libopengl0
          fi

      - name: Run Tests
        run: uv run pytest -vvx
