name: Windows Tests

on: [push]

jobs:
  build:
    name: Pruebitas en Win
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare Environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install . --upgrade
      - name: Format
        run: |
          black src/ tests/ --check
      - name: PEP8
        run: |
          flake8 src/pireal --config=.flake8
      - name: unittest
        run: |
          pytest -v tests/unit
      - name: integration tests
        run: |
          pytest -v tests/integration
