name: Linux Tests

on: [push]

jobs:
  build:
    name: Pruebitas en Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare Environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install . --upgrade
      - name: Lint
        run: |
          make lint
      - name: unittests
        run: |
          make test-unit
      - name: interpreter tests
        run: |
          make test-interpreter
      - name: integration tests
        run: |
          make test-integration
